config/routes.rb
Rails.application.routes.draw do

get "home" => "posts#home"
get "signup" => "users#new"  
get "signin" => "sessions#new"

	resources :posts
	resources :users
	resources :sessions


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 

  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    params.permit!
     @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_path, :notice => "Posted successfully"
    else
      render "new"
    end
  end

   def edit
    @post = Post.find(params[:id])
  end

  def update
    params.permit!
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to posts_path, :notice => "Updated"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
   redirect_to posts_path, :notice => "Deleted"
  end

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to :controller=>'posts',:action=>'index'
  	else
  		render "new"
  	end

  end

  def destroy
  	session[:user_id] = nil
  	redirect_to :controller=>'users',:action=>'index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
def index
end
	
def new
	@user = User.new
end

def create
	params.permit!

	@user = User.new(params[:user])
	if @user.save
		redirect_to :controller=>'users',:action=>'index'
	else
		render "new"
	end
end

end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Log</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
 
<div class = "log">
  <% if current_user %>
  		Logged in as <%= current_user.email %>
  		<%=	 link_to "Logout", session_path("current"), method: "delete", style: 'color:#FFFFFF'%>
  <% else %>

  		<%=	 link_to "Sign Up", new_user_path, style: 'color:#FFFFFF' %> |
  		<%=	 link_to "Log In", new_session_path, style: 'color:#FFFFFF' %>
 <% end %>

</div>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<body class = "post_new">
<h1>Edit</h1>

<%= form_for @post do |f| %>
<p>
  <%= f.label  :Title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label  :"Content" %><br>
  <%= f.text_area :content, :class => "textarea"%>
</p>

<p>
   <%= f.submit :Done, :class => "button" %>
</p>

<% end %>
</body>

app/views/posts/home.html.erb
<body class ="home">
<center><h1>WELCOME</h1></center>
</body>

app/views/posts/index.html.erb
<body class = "post_index">
<center><h1>DASHBOARD</h1></center>

<div align="right">
  <h2><%= link_to "Add a New Note", new_post_path, style: 'color:#FFFFFF' %></h2>
</div>
<% @posts.each do |p| %>
<p>
	<h1><%=  link_to p.title, post_path(p), style: 'color:#FFFFFF' %></h1>
	 <%= p.content %>
</p>


	 <%= link_to "Edit", edit_post_path(p), style: 'color:#FFFFFF' %> |
	 <%=  link_to "Delete", p, style: 'color:#FFFFFF', :method => :delete %>
	<hr>


<% end %>
</body>
 
 <%# <%= link_to "home", '/home'  %> 

app/views/posts/new.html.erb
<h2> WEB NOTE</h2>
<body class = "post_new">

<%= form_for @post do |f| %>
<p>
  <%= f.label  :Title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label  :"Content" %><br>

  <%= f.text_area :content ,:class => "textarea" %> 
</p>

<p>
   <%= f.submit :Post, :class => "button" %>
</p>

<% end %>
</body>	

app/views/posts/show.html.erb
<h1>Show Page</h1>

<h2><%= @post.title %></h2>
<p><%= @post.content %></p>
<small><%= @post.created_at %></small> 	

app/views/users/index.html.erb
<body class = "user_index">

<center><h1>See Ya..!!</h1></center>

</body>

app/views/users/new.html.erb
<body class="Sign_Form" >

<h1><p style="margin-left:3em;">Sign up</p></h1>
    <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Name</br> <%= f.text_field :name %> </p>
    <p> Email</br> <%= f.text_field :email %> </p>
    <p> Password</br> <%= f.password_field :password %></p>
    <p> Password Confirmation</br> <%= f.password_field :password_confirmation %> </p>
    <%= f.submit :SignUp , :class => "button_signup" %>  
  <% end %>
  </div>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</body>